#!/usr/bin/env ruby
require 'thor'

module Rosalind
  class Create < Thor::Group
    include Thor::Actions

    argument :question, :type => :string, :desc => 'The title of the question'

    def process
      name = question.strip.downcase.gsub(' ', '_')
      base_path = File.join('problems', name)
      create_file(File.join(base_path, 'solution.rb')) do
        <<-EOF
# Problem: #{question}

dataset = File.read('dataset.txt')
EOF
      end

      create_file(File.join(base_path, 'dataset.txt'))
    end
  end
end

Rosalind::Create.start
