#!/usr/bin/env ruby
require 'thor'

module Rosalind
  class Create < Thor
    include Thor::Actions

    def self.source_root
      File.dirname(__FILE__)
    end

    desc 'bio QUESTION [opts]', 'create a new bioinformatics question'
    option :fasta, aliases: '-f', type: :boolean, default: false, desc: 'include fasta helper'
    def bio(question)
      @question = question
      @name = question.strip.downcase.gsub(' ', '_')
      base_path = File.join('problems', 'bioinformatics', @name)

      template('templates/bioinformatics/solution.rb.erb', File.join(base_path, 'solution.rb'))

      create_file(File.join(base_path, 'dataset.txt'))
    end

    desc 'bio QUESTION [opts]', 'create a new algorithm question'
    def algo(question)
      @question = question
      @name = question.strip.downcase.gsub(' ', '_')
      base_path = File.join('problems', 'algorithms', @name)

      template('templates/algorithms/solution.rb.erb', File.join(base_path, 'solution.rb'))

      create_file(File.join(base_path, 'dataset.txt'))
    end
  end


end

Rosalind::Create.start
